import type { Metadata } from "next";
import localFont from "next/font/local";

import ProviderLayout from "@/layouts/ProviderLayout";
import "../styles/globals.css";

const pretendard = localFont({
  src: [
    {
      path: "../../public/fonts/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

// TODO: metadata 설정 변경
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="text-16-m">
        <ProviderLayout>{children}</ProviderLayout>
      </body>
    </html>
  );
}
